$:.push File.expand_path('../lib', __FILE__)
require 'rubygems'

require 'bundler/setup'

require 'bundler/gem_tasks'
require 'rake/testtask'
require 'thor/rake_compat'

class Default < Thor
  class Gem < Thor
    include Thor::RakeCompat
    Bundler::GemHelper.install_tasks

    namespace :gem

    desc "build", "Build vagrant-berkshelf-#{Berkshelf::Vagrant::VERSION}.gem into the pkg directory"
    def build
      Rake::Task["build"].execute
    end

    desc "release", "Create tag v#{Berkshelf::Vagrant::VERSION} and build and push vagrant-berkshelf-#{Berkshelf::Vagrant::VERSION}.gem to Rubygems"
    def release
      Rake::Task["release"].execute
    end

    desc "install", "Build and install vagrant-berkshelf-#{Berkshelf::Vagrant::VERSION}.gem into system gems"
    def install
      Rake::Task["install"].execute
    end
  end

  class Spec < Thor
    include Thor::RakeCompat
    Rake::TestTask.new :spec do |task|
      task.libs << 'spec'
      task.test_files = FileList['spec/**/*_spec.rb']
    end

    desc 'ci', 'Run all tests for continuous integration'
    def ci
      ENV['CI'] = 'true'
      invoke(:unit)
    end

    desc 'spec', 'Run specs'
    def spec
      Rake::Task['spec'].execute
    end
  end
end

